#Endpoints para user_ms

#Endpoint: Hola mundo!!!

GET http://127.0.0.1:8000
Authorization: Bearer 12345

### Consultar todos los usuarios 

GET /http://127.0.0.1:8000/users/
Authorization: Bearer 12345

### Consultar un usuario por ID
GET http://127.0.0.1:8000/users/3
Authorization: Bearer 12345

#### Crear un nuevo usuario
POST http://127.0.0.1:8000/users/
Content-Type: application/json
Authorization: Bearer 12345

{
    "user": "testUser",
    "pwd": "12345"
}

### modificar usuario
PUT http://127.0.0.1:8000/users/8
Content-Type: application/json
Authorization: Bearer 12345

{
    "user": "pepe",
    "pwd": "1234567"
}

### eliminar usuario
DELETE http://127.0.0.1:8000/users/8
Authorization: Bearer 12345
CODE-Validation: 789